# This is a basic workflow to help you get started with Actions

name: Cypress Tests using Cypress Docker Image

on:
  push:
    branches: ["practise"]

jobs:
  cypress-run:
    time-out minutes : 15
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
     steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

        with:
          # Specify Browser since container image is compile with Firefox
          browser: electron
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          GITHUB-TOKEN: ${{secrets.GITHUB_TOKEN}}
